const handler = async (m, {conn}) => {
  m.reply(global.SpamLink);
};
handler.command = /^(SpamLink|SpamLink)$/i;
export default handler;
handler.admin = true
handler.group = true
handler.botAdmin = true

global.SpamLink = `〔 𝗢𝗽𝘁𝗶𝗺𝘂𝘀 𝗕𝗼𝘁 〕


𝐋𝐈𝐍𝐊 𝐒𝐏𝐀𝐌 𝐖𝐇𝐀𝐓𝐒𝐀𝐏𝐏 : https://www.mediafire.com/file/elvm4t2m0tf25ux/SPAM_WHATSAPP.apk/file

𝗟𝗜𝗡𝗞𝗦 𝗗𝗘 𝗖𝗢𝗠𝗨𝗡𝗜𝗗𝗔𝗗𝗘𝗦 :
https://chat.whatsapp.com/CP9eIdCQdeICMZPb2yAOY2
https://chat.whatsapp.com/LLIViD8u5ikGcQJDVbHur2
https://chat.whatsapp.com/Hl4182CYTps33aVYUzlSgf
https://chat.whatsapp.com/Jjkr2yyOEWFDR3UtWJxCYB
https://chat.whatsapp.com/JTApoj7DN5gFxp9IiifnLZ
https://chat.whatsapp.com/Hl6Y77Rvjfz1wZ8HdSuXBE
https://chat.whatsapp.com/FQWlkpoCDd549KpV1rXBKu
https://chat.whatsapp.com/FQWlkpoCDd549KpV1rXBKu
https://chat.whatsapp.com/JLefQax4S2yHTDcviuxdcE
https://chat.whatsapp.com/IDTvKGITKCACegO15lNDuT
https://chat.whatsapp.com/LHXPoyVfODa8BlhmkY8inm
https://chat.whatsapp.com/L23UutYDijz4Z75RBKRRqw
https://chat.whatsapp.com/Eou1xNO2KzVEey7w6ulj8P
https://chat.whatsapp.com/Kkc5nFyrZCh6zmIj4EScBh
https://chat.whatsapp.com/GfoTrxWhUWM6si0pzR6wDP
https://chat.whatsapp.com/GBgUJ1WCuIYBemPH0c9vIU
https://chat.whatsapp.com/DB03Fg8h9101upMqTgUY6o
https://chat.whatsapp.com/HzfMc9C3UjL8Cksp0hF0ql
https://chat.whatsapp.com/BZ9w5UN47Qw5KhQWVyJ9V4
https://chat.whatsapp.com/KQZLWNOLa9cAtEUGWwFlS3
https://chat.whatsapp.com/GjB1WVODjPHDE7fKWmRjh2
https://chat.whatsapp.com/KMlisnP6Ul878qmtOkcxdl
https://chat.whatsapp.com/C5t5Q4y8D3KCETXtRUP7Wh
https://chat.whatsapp.com/HWa1kHEDmeS0jZ5074qKyH
https://chat.whatsapp.com/IQohqJPmLjv8jOZk1Co9Kb
https://chat.whatsapp.com/H4u6RWh8pLsJOf5JDXemdG
https://chat.whatsapp.com/Cc0mLNUemyR7BUq6h2Lug3
https://chat.whatsapp.com/CmTG1Ozz5RP6lF7kCeSEKP
https://chat.whatsapp.com/F67pLYNDKiL91xMjn2f22n
https://chat.whatsapp.com/FhQNm8oh4gYHrWRUC7a20p
https://chat.whatsapp.com/I6Bo1D4LM6r8QWPQg9MBKL
https://chat.whatsapp.com/JcTDvQT1GL08tfHfSmAy2q
https://chat.whatsapp.com/BfvMSEXAub69JH7CNAS7bR
https://chat.whatsapp.com/HoH2a68pPI0GFyjDWrkryY
https://chat.whatsapp.com/Jbmyq2DLfej3DCDvc9p0lW
https://chat.whatsapp.com/L7clDUaZD5qH0bcigUvQ24
https://chat.whatsapp.com/GvkMuHhqykRJvTkfZfgT0X
https://chat.whatsapp.com/ELt5fS5hKa86WbPnPbJVXB
https://chat.whatsapp.com/IMwqNXri9CT3mN7GtfdDjt
https://chat.whatsapp.com/G08MJsa2ZFrEHilrFFSHno
https://chat.whatsapp.com/LLHH0PIZj7E4IFLOQyjOnR
https://chat.whatsapp.com/FGSvGZH2ISA0S933YjscQ3
https://chat.whatsapp.com/LvwgOsez4vK1YgS3OmVnkL
https://chat.whatsapp.com/LjLcjYm2BWQ8ndPompLXEA
https://chat.whatsapp.com/IpBslU1f1d5DpqUygVUzA2
https://chat.whatsapp.com/G408poiN1GgIy76Rns04gv
https://chat.whatsapp.com/KSXEi7PI53AKIwrfK6E0co
https://chat.whatsapp.com/L0w7NNBIIJpKQSyB7BQvGb
https://chat.whatsapp.com/Ln8luImvgF05X0XNghtV74
https://chat.whatsapp.com/CGYWuozPN4wB1FdXhEIGJp
https://chat.whatsapp.com/E4Z0Fek2oFdHChpJCCdSvl
https://chat.whatsapp.com/IIjZwtat7QT7KHZ4MSD0IE
https://chat.whatsapp.com/JVeqQzfSxqYCdOgJuHTcct
https://chat.whatsapp.com/LTVtZjqslkK5o4I3uu5cgS
https://chat.whatsapp.com/HYjTDFyA9r72DvvRxxlSp4
https://chat.whatsapp.com/LTVtZjqslkK5o4I3uu5cgS
https://chat.whatsapp.com/LM1LHcVwycqC6W1Z6hJf8i
https://chat.whatsapp.com/JRLhziQQ5QdL9YVT5IvRgt
https://chat.whatsapp.com/CndwoY93KiWHsYYtPh9Rmi
https://chat.whatsapp.com/FGaRrspBhBd8jPpBdzOV2q
https://chat.whatsapp.com/FIBLTiPfFWjKvVnrkbNqKa
https://chat.whatsapp.com/BvggwIXT35N6rNCuiiN2uV
https://chat.whatsapp.com/Ix3Qc4X3DBoCa0Pkk3uxTn
https://chat.whatsapp.com/IrfblO4WlkY9okUC90A17g
https://chat.whatsapp.com/Ls9B4wT3KqB0fh93yCoDcz
https://chat.whatsapp.com/Jqa4sa2es6BITmBuU9frGP
https://chat.whatsapp.com/DqdSEDolbC3IroVd3OZ9BH
https://chat.whatsapp.com/DJ7iS5iQbleC8KKn1knyrC
https://chat.whatsapp.com/H2qviAxkIPuBWoClwCgfmS
https://chat.whatsapp.com/BHAqItA193V7ymmZ0tkLMS
https://chat.whatsapp.com/CLeoaOHpW0VGCGyjkzT4LX
https://chat.whatsapp.com/DAkDY8CbTRuDqyiKuF7onj
https://chat.whatsapp.com/GPaLIJs1Ivg5Is68kXxQVH
https://chat.whatsapp.com/CVyI0VQOox5591P15N0gEm
https://chat.whatsapp.com/BqWC02MERcuKRGFGmqykHv
https://chat.whatsapp.com/DYtXaGUhG40K6KRGz9izag
https://chat.whatsapp.com/JcyFgST1XHS9FZzdn4jrtV
https://chat.whatsapp.com/IdVR3lnxZY2LCmzwfcjEYC
https://chat.whatsapp.com/CcpjjUD72FSJLzEXD9Iz1T
https://chat.whatsapp.com/I31UlRdqoKDLwBZ7aGgkNH
https://chat.whatsapp.com/Igz8Cj7eo8l1CBSnXbAQHa
https://chat.whatsapp.com/KZvOFLAzlV7AYiVQdg5lI5
https://chat.whatsapp.com/JEJQQMReQFR8qyHWyP2GvH
https://chat.whatsapp.com/CmsgwkFsNXY9KXWea5SjZI
https://chat.whatsapp.com/FTqYGNLIcY2JafBVnlpnZe
https://chat.whatsapp.com/LM1LHcVwycqC6W1Z6hJf8i
https://chat.whatsapp.com/KwakMwet6aF7HnMqqTbdU1
https://chat.whatsapp.com/D3cp1JrW9fIIhQCk5mkNAw
https://chat.whatsapp.com/HLj2szMinAE5mx3YXKKOWS
https://chat.whatsapp.com/BcN7rY7v0GK4klLte7y7f2
https://chat.whatsapp.com/EUeiumHFj3PJBTc3pkvpFy
https://chat.whatsapp.com/EEuygEySC0vFAGLHhGhko7
https://chat.whatsapp.com/GPNYWwuHEgp2Kgmb4eIHwb
https://chat.whatsapp.com/CEuuXxfOsam1W8RjaTJLcs
https://chat.whatsapp.com/IkLOEzQbJ32CaCRKHqEt1U
https://chat.whatsapp.com/DKN13i3gejcFTa6qJgVmiE
https://chat.whatsapp.com/CEcFJKqYQ8eBZFvJk29xmR
https://chat.whatsapp.com/HoYs6Z3ufLl9cMJuFMUyrU
https://chat.whatsapp.com/CmsgwkFsNXY9KXWea5SjZI
https://chat.whatsapp.com/Ll1F8j7ltg7CB9dU49D2Xz
https://chat.whatsapp.com/Ix3Qc4X3DBoCa0Pkk3uxTn
https://chat.whatsapp.com/Epuk3K9uWluKeSHGVfk9qG
https://chat.whatsapp.com/D86cW6Y3lOv8b7wCSm125d
https://chat.whatsapp.com/ErZWlzK8VdsD5u388lphHF
https://chat.whatsapp.com/LszOKGCODSlE8utorfBNvS
https://chat.whatsapp.com/KnZjH4Xk9nx5B4icqm7FpZ
https://chat.whatsapp.com/BlbJrya1XpXKG2QyllsX9i
https://chat.whatsapp.com/E0nM5mLaYuC4QLC9FRqskM
https://chat.whatsapp.com/Gi2G6UdHpoi0pBbiitEj8M
https://chat.whatsapp.com/HoYs6Z3ufLl9cMJuFMUyrU
https://chat.whatsapp.com/EvuzVssuC7fAAQwwezveMA
https://chat.whatsapp.com/Ib41AFsbvgT5vpjYVhTpaq
https://chat.whatsapp.com/DiJM597mWNxB7loZldKJLu
https://chat.whatsapp.com/IXmb6LNkgYfFM1MWsGLNQs
https://chat.whatsapp.com/Kmyqktz0qDQ4z6iXaqiIQ4
https://chat.whatsapp.com/LWZn5BO23GHJJaaVGD4A9h
https://chat.whatsapp.com/I1wu2zl6OEcHXhIf5fnOvr
https://chat.whatsapp.com/GpRVpGQp2am5MDIGevsHdV
https://chat.whatsapp.com/KzX846trtIsDiXWWR3LG30
https://chat.whatsapp.com/BdnNQxJyhBi9iM7RAN4zJO 
https://chat.whatsapp.com/JVVO82XC9Mo2nOY2ELJvle 
https://chat.whatsapp.com/FrRCtlhZn4b1AJPnSI6XPi 
https://chat.whatsapp.com/G6dQhGudCcVHsqSHeQzDI0
https://chat.whatsapp.com/JuOiTfE2rPf8QK9ivOozid
https://chat.whatsapp.com/BwDkfQCVGXNKgK5dvEaU2s
https://chat.whatsapp.com/B6qW3lgLh6x7iSqrEwGBX7
https://chat.whatsapp.com/E6LlaPDocKu37Xvirgsu9B
https://chat.whatsapp.com/L1OqEUFYuzY7IrKfElfTGD
https://chat.whatsapp.com/GxxXRGF20pE2IVvI4tfS3S
https://chat.whatsapp.com/JiKkBG9MQDYB8XbQxJYob5
https://chat.whatsapp.com/Gob4gXKYMwyDvxJQV1G5cl
https://chat.whatsapp.com/I727QzS6RoaCKRSvA0RRve
https://chat.whatsapp.com/FJ7yfQRUiPnJ6ybDFUvjN3
https://chat.whatsapp.com/DjsFrUdpqQ4IHWtIl88IsK
https://chat.whatsapp.com/Gt2W0GCeppZCcTP21J3zK8
https://chat.whatsapp.com/IaTZhzEkGQv9bhkif1YxoT
https://chat.whatsapp.com/I25CpP65F7nHetZvTKzOOr
https://chat.whatsapp.com/CjA8e5Ji5urALJvL1SUCcA
https://chat.whatsapp.com/JNSQ3dtHcS8EKycPdBE6Cr
https://chat.whatsapp.com/K2qvhDql4kw94rO4dsyaGL
https://chat.whatsapp.com/EzgHbhwHEymG6se8uu0lfu
https://chat.whatsapp.com/LDB9yHpu67oHMszwxHGUPV
https://chat.whatsapp.com/BGXRaJhptfp6ZPZOJ900r2
https://chat.whatsapp.com/EPscuTs17wKLpxaPBLYidV
https://chat.whatsapp.com/EZuNXTEuRaiH95bmPv1Lbc
https://chat.whatsapp.com/GP5dIGnhSPNBmatycitdR1
https://chat.whatsapp.com/Ef4K6wyXuXuIjJ6wxsHxzr
https://chat.whatsapp.com/D8IiSflmobc1cnbVpao7y2
https://chat.whatsapp.com/ICCit4HnXx98cPGZey2Oe6
https://chat.whatsapp.com/JAUU1mtxPpoJMp1K4bcXfz
https://chat.whatsapp.com/Be9G0f3KXDH7NJMqZrNuA2
https://chat.whatsapp.com/LDB9yHpu67oHMszwxHGUPV
https://chat.whatsapp.com/GkbXWyA9RnR9q1sKycfUZ4
https://chat.whatsapp.com/JUFESLY0dgxHZJsY8fArbW
https://chat.whatsapp.com/ENH1z0nUxzOC2W3BalAFkC
https://chat.whatsapp.com/G5MBW5QKaRl6HJhMl7hTwz
https://chat.whatsapp.com/GK2i45wZztAD7JU4KiaPAJ
https://chat.whatsapp.com/BSpjJhcEIcQDjX49vzluH5
https://chat.whatsapp.com/CsyMLiljrLILQJvqmaRDV9
https://chat.whatsapp.com/GTxxRwWKJTRJUJI1rsuCUu
https://chat.whatsapp.com/F6nUumtHmnq2v97Cd6Vnyt
https://chat.whatsapp.com/FdKMMQTEasq73PAkoSxHpL
https://chat.whatsapp.com/FD2CeNrDcIK9TajngVZwO3	
https://chat.whatsapp.com/H0qYvpa8UyrLADx1g1P91z					
https://chat.whatsapp.com/GNVAjGoIcarGvVndVYGXmt					
https://chat.whatsapp.com/F1rEHU7MOTM4oDFcKaT9ff					
https://chat.whatsapp.com/ExhE2X8Ac6O3f3PcRBmLWj					
https://chat.whatsapp.com/LMetrLYqSkFFDc8auQEpko					
https://chat.whatsapp.com/J6Xnr1m4zNxEdpJ4PyCWKi					
https://chat.whatsapp.com/FWCIqsZ7BqHDGFTDkyrT6H					
https://chat.whatsapp.com/JxlRyNGgYynCyS51fzW5QJ					
https://chat.whatsapp.com/JB14c4wRxoE2Qkb3qIqVVw				
https://chat.whatsapp.com/DTCxZNBWjrI5ZYaArFn8DI				
https://chat.whatsapp.com/HTCkwPhyMAG6QGCoBatncO					
https://chat.whatsapp.com/I13xPvfmLSy3JVxFrPwUyc				
https://chat.whatsapp.com/L2ISSEfNHLkCzvp6MzYMRN					
https://chat.whatsapp.com/J7tEBBN9Pka48RTSkcoUrZ				
https://chat.whatsapp.com/L5bfXZHEtoDF1631LAklOo					
https://chat.whatsapp.com/FyAtGSywLa18SP2zgLDtS7					
https://chat.whatsapp.com/FdVtpCSGtrkDTfuoQ66ETG					
https://chat.whatsapp.com/LkFWQG1Ie6Q0zs2Yh4UtyQ					
https://chat.whatsapp.com/E6kLV0M2CF1F0gYze4sEFB					
https://chat.whatsapp.com/IXhTqiu08MH0w5gn4bs3gs					
https://chat.whatsapp.com/Fre6Cf9aVKYCRpL1Syandx				
https://chat.whatsapp.com/LZODSnfXK23DHKZ8Psx9s8					
https://chat.whatsapp.com/HBEyNah2fk1I56Il4ggFPl					
https://chat.whatsapp.com/L3TmIaBFVmk2WJqLSKkrYp					
https://chat.whatsapp.com/B5Pc1CP5Wgp7o3MPwfwzCC			
https://chat.whatsapp.com/JG8vHZFs2rf0RTDEAJMi45					
https://chat.whatsapp.com/DgQ9DZaiLcSBjcjiHSUnAO					
https://chat.whatsapp.com/Hmf8K81JITXCh5Fh14kPuj					
https://chat.whatsapp.com/EKtXFKUQMrVLQpRN5IwGR5					
https://chat.whatsapp.com/Ck4eiJoTAYX0PCgOW3cDhZ					
https://chat.whatsapp.com/GtzOzCUy7OCAaBDT6K61Tt					
https://chat.whatsapp.com/JWWu9LgOKSkAVxiY3haB7W					
https://chat.whatsapp.com/JyXeAyEL6OeLyEK2rhZt3D					
https://chat.whatsapp.com/DbYIJ56GfVrHaDYSXzVGMA					
https://chat.whatsapp.com/E2A3QFQ6AwX6hYAikQW07o					
https://chat.whatsapp.com/ITB0Nv4ysir4hRCsI8eerP					
https://chat.whatsapp.com/LsC34bJIsqi4A6zs34Cyfh					
https://chat.whatsapp.com/JjhCllYE6xAGcxiPOOrPtz					
https://chat.whatsapp.com/CKASLVEdURtJj5UGELootr					
https://chat.whatsapp.com/Lddy9PS2j53CFBo9WtTl5T
https://chat.whatsapp.com/GauuiJOcKUoLWMDyFXFYJp					
https://chat.whatsapp.com/Ea74LGI7LudDh71ivHzfU6					
https://chat.whatsapp.com/BFJ9yFOAZvFLegXUpLnDBO					
https://chat.whatsapp.com/KpTSqTMdtTcBqPbaf5k2ZO					
https://chat.whatsapp.com/BgUygm1tOQPDDzQ8XE5OBR					
https://chat.whatsapp.com/GGXSp5fcHY36eEE8LIgb39					
https://chat.whatsapp.com/FE6CkEnc4bJB1eyu7EwIYm					
https://chat.whatsapp.com/DEpametGTpAAPP1ZFTAVrq					
https://chat.whatsapp.com/D6oy9Nt6QFpD3ny3FQtsya
https://chat.whatsapp.com/GyK0XGVZoEM2fy20qDzMDi
https://chat.whatsapp.com/CmLJkCvDQdEHGFKgyneFbZ
https://chat.whatsapp.com/KWidEUwXgkS4sAH3GlJ3oG
https://chat.whatsapp.com/IwJFkBgNVQCE8jPMQg1uuZ
https://chat.whatsapp.com/LpVKFkVz2awH9aqgIxPCfZ
https://chat.whatsapp.com/HzqwMa0bOwzGbCYH9VvV
https://chat.whatsapp.com/KTj0WKMdXCOJFR9q7f7vLB					
https://chat.whatsapp.com/J3G1OmGbsB3FDSf8ubGAH0					
https://chat.whatsapp.com/HJvzFkz3zwf2kGNTTKShHY					
https://chat.whatsapp.com/LFOcX6G8mDiFVoUgL5o6kb					
https://chat.whatsapp.com/GUMHTNNBVCR1lT3BBot6EJ					
https://chat.whatsapp.com/HudKXsnU2iB7ic3sH7nb4G					
https://chat.whatsapp.com/ClDQKHjxUqaCzJSMJjLk29					
https://chat.whatsapp.com/LJQI3E82xl20072pLJXncf					
https://chat.whatsapp.com/HZGeiv2XvIiEFZKsXAZZbh					
https://chat.whatsapp.com/IkzYJfnJFsvJ6Qjz7Pffwy					
https://chat.whatsapp.com/FEjk7Vi7jjX8Olrs1ZeARX					
https://chat.whatsapp.com/LuNGiC3ypBF2ASYfbIFw8d					
https://chat.whatsapp.com/JvkiUZtWNRO6Jdq1wxegVi					
https://chat.whatsapp.com/DU9TBC8iYx3E9silzXIDCV					
https://chat.whatsapp.com/CR971xWwjeB6eI6YLXzv9g					
https://chat.whatsapp.com/H3Qgkw0qQDjK4T2KErFT7F					
https://chat.whatsapp.com/DrOlNRBju4P1lYCzJUHAqL					
https://chat.whatsapp.com/HKz2AxOPEdRJrttkNfJNlp					
https://chat.whatsapp.com/FGfMjqPEpNE5IOo4xEFOgj					
https://chat.whatsapp.com/LpyXCEny526Ffokx4KSpSE					
https://chat.whatsapp.com/Cqi0luQB3MEBsrS9xDIQvi					
https://chat.whatsapp.com/GnqfN2zxvwl3G8CuMQGc3x					
https://chat.whatsapp.com/CBJcz0jfX21DYH0mECjssj					
https://chat.whatsapp.com/GFFgcGnTCoYAvJvqRbJUKN					
https://chat.whatsapp.com/BANuP8vkjcSADolQeinbbj					
https://chat.whatsapp.com/HmKM7QJNsab9odVaLHgjjp					
https://chat.whatsapp.com/CQhHW2UGSg0GrilCdKhQhD					
https://chat.whatsapp.com/CeWneN96YHm1R4quNCZntC				
https://chat.whatsapp.com/GaUKgDxo4bjAuWHNxm5oAb					
https://chat.whatsapp.com/FPSdOCW7kZ3KHeI9qeAyW3					
https://chat.whatsapp.com/DMeGjb1Z32l0Rs3OjwOcaG					
https://chat.whatsapp.com/LVQUzuLzaCgCyjofqjV5n6					
https://chat.whatsapp.com/IW5lqjKwGElAVoal6LRsRQ					
https://chat.whatsapp.com/EZcR5FRCJla3lGSdc9Qmii					
https://chat.whatsapp.com/Jv5MagdGoRy3ZIGcCrIHl8					
https://chat.whatsapp.com/FeWI4mKrHpF1SsWf0ZGkU5				
https://chat.whatsapp.com/FZkCQ2osgHYJe0aWA7T5SE				
https://chat.whatsapp.com/C6oj5xS7Neu2dbsAvv3CrR					
https://chat.whatsapp.com/JNm7XbaibO75vjeDiGU1EW					
https://chat.whatsapp.com/CPpLSiKxxz03Ux0eHI2v3N				
https://chat.whatsapp.com/KmofKAdxEgyCBVE3WnpQjf					
https://chat.whatsapp.com/Bn3sVDdwtZA0Ujx0D24A6u					
https://chat.whatsapp.com/BYKlNWtxtTzDBw0SDQUc3O					
https://chat.whatsapp.com/JXidsS8tXylCIqiGc6t0TV					
https://chat.whatsapp.com/Id3S3lnfgUJ3z0vmIIUqK5					
https://chat.whatsapp.com/KXNiV4kzMXYFQrbKQ8p4Bw					
https://chat.whatsapp.com/GyJfA7tgGwK2i74RHFFROb					
https://chat.whatsapp.com/FsRcqaYtvNr6lJhtSDFzJ3					
https://chat.whatsapp.com/GBFo8kKXyt925aQl5JfM65					
https://chat.whatsapp.com/FIjOgGSnRvS0jkiy6B6tHZ
`;
