const handler = async (m, {conn}) => {
  m.reply(global.SpamLink);
};
handler.command = /^(SpamComu)$/i;
export default handler;
global.SpamLink = `

𝗟𝗜𝗡𝗞𝗦 𝗗𝗘 𝗖𝗢𝗠𝗨𝗡𝗜𝗗𝗔𝗗𝗘𝗦

https://chat.whatsapp.com/H2qviAxkIPuBWoClwCgfmS
https://chat.whatsapp.com/BHAqItA193V7ymmZ0tkLMS
https://chat.whatsapp.com/CLeoaOHpW0VGCGyjkzT4LX
https://chat.whatsapp.com/DAkDY8CbTRuDqyiKuF7onj
https://chat.whatsapp.com/GPaLIJs1Ivg5Is68kXxQVH
https://chat.whatsapp.com/CVyI0VQOox5591P15N0gEm
https://chat.whatsapp.com/BqWC02MERcuKRGFGmqykHv
https://chat.whatsapp.com/DYtXaGUhG40K6KRGz9izag
https://chat.whatsapp.com/JcyFgST1XHS9FZzdn4jrtV
https://chat.whatsapp.com/IdVR3lnxZY2LCmzwfcjEYC
https://chat.whatsapp.com/CcpjjUD72FSJLzEXD9Iz1T
https://chat.whatsapp.com/I31UlRdqoKDLwBZ7aGgkNH
https://chat.whatsapp.com/Igz8Cj7eo8l1CBSnXbAQHa
https://chat.whatsapp.com/KZvOFLAzlV7AYiVQdg5lI5
https://chat.whatsapp.com/JEJQQMReQFR8qyHWyP2GvH
https://chat.whatsapp.com/CmsgwkFsNXY9KXWea5SjZI
https://chat.whatsapp.com/FTqYGNLIcY2JafBVnlpnZe
https://chat.whatsapp.com/LM1LHcVwycqC6W1Z6hJf8i
https://chat.whatsapp.com/KwakMwet6aF7HnMqqTbdU1
https://chat.whatsapp.com/D3cp1JrW9fIIhQCk5mkNAw
https://chat.whatsapp.com/HLj2szMinAE5mx3YXKKOWS
https://chat.whatsapp.com/BcN7rY7v0GK4klLte7y7f2
https://chat.whatsapp.com/EUeiumHFj3PJBTc3pkvpFy
https://chat.whatsapp.com/EEuygEySC0vFAGLHhGhko7
https://chat.whatsapp.com/GPNYWwuHEgp2Kgmb4eIHwb
https://chat.whatsapp.com/CEuuXxfOsam1W8RjaTJLcs
https://chat.whatsapp.com/IkLOEzQbJ32CaCRKHqEt1U
https://chat.whatsapp.com/DKN13i3gejcFTa6qJgVmiE
https://chat.whatsapp.com/CEcFJKqYQ8eBZFvJk29xmR
https://chat.whatsapp.com/HoYs6Z3ufLl9cMJuFMUyrU
https://chat.whatsapp.com/CmsgwkFsNXY9KXWea5SjZI
https://chat.whatsapp.com/Ll1F8j7ltg7CB9dU49D2Xz
https://chat.whatsapp.com/Ix3Qc4X3DBoCa0Pkk3uxTn
https://chat.whatsapp.com/Epuk3K9uWluKeSHGVfk9qG
https://chat.whatsapp.com/D86cW6Y3lOv8b7wCSm125d
https://chat.whatsapp.com/ErZWlzK8VdsD5u388lphHF
https://chat.whatsapp.com/LszOKGCODSlE8utorfBNvS
https://chat.whatsapp.com/KnZjH4Xk9nx5B4icqm7FpZ
https://chat.whatsapp.com/BlbJrya1XpXKG2QyllsX9i
https://chat.whatsapp.com/E0nM5mLaYuC4QLC9FRqskM
https://chat.whatsapp.com/Gi2G6UdHpoi0pBbiitEj8M
https://chat.whatsapp.com/HoYs6Z3ufLl9cMJuFMUyrU
https://chat.whatsapp.com/EvuzVssuC7fAAQwwezveMA
https://chat.whatsapp.com/Ib41AFsbvgT5vpjYVhTpaq
https://chat.whatsapp.com/DiJM597mWNxB7loZldKJLu
https://chat.whatsapp.com/IXmb6LNkgYfFM1MWsGLNQs
https://chat.whatsapp.com/Kmyqktz0qDQ4z6iXaqiIQ4
https://chat.whatsapp.com/LWZn5BO23GHJJaaVGD4A9h
https://chat.whatsapp.com/I1wu2zl6OEcHXhIf5fnOvr
https://chat.whatsapp.com/GpRVpGQp2am5MDIGevsHdV
https://chat.whatsapp.com/KzX846trtIsDiXWWR3LG30
https://chat.whatsapp.com/BdnNQxJyhBi9iM7RAN4zJO 
https://chat.whatsapp.com/JVVO82XC9Mo2nOY2ELJvle 
https://chat.whatsapp.com/FrRCtlhZn4b1AJPnSI6XPi 
https://chat.whatsapp.com/G6dQhGudCcVHsqSHeQzDI0
https://chat.whatsapp.com/JuOiTfE2rPf8QK9ivOozid
https://chat.whatsapp.com/BwDkfQCVGXNKgK5dvEaU2s
https://chat.whatsapp.com/B6qW3lgLh6x7iSqrEwGBX7
https://chat.whatsapp.com/E6LlaPDocKu37Xvirgsu9B
https://chat.whatsapp.com/L1OqEUFYuzY7IrKfElfTGD
https://chat.whatsapp.com/GxxXRGF20pE2IVvI4tfS3S
https://chat.whatsapp.com/JiKkBG9MQDYB8XbQxJYob5
https://chat.whatsapp.com/Gob4gXKYMwyDvxJQV1G5cl
https://chat.whatsapp.com/I727QzS6RoaCKRSvA0RRve
https://chat.whatsapp.com/FJ7yfQRUiPnJ6ybDFUvjN3
https://chat.whatsapp.com/DjsFrUdpqQ4IHWtIl88IsK
https://chat.whatsapp.com/Gt2W0GCeppZCcTP21J3zK8
https://chat.whatsapp.com/IaTZhzEkGQv9bhkif1YxoT
https://chat.whatsapp.com/I25CpP65F7nHetZvTKzOOr
https://chat.whatsapp.com/CjA8e5Ji5urALJvL1SUCcA
https://chat.whatsapp.com/JNSQ3dtHcS8EKycPdBE6Cr
https://chat.whatsapp.com/K2qvhDql4kw94rO4dsyaGL
https://chat.whatsapp.com/EzgHbhwHEymG6se8uu0lfu
https://chat.whatsapp.com/LDB9yHpu67oHMszwxHGUPV
https://chat.whatsapp.com/BGXRaJhptfp6ZPZOJ900r2
https://chat.whatsapp.com/EPscuTs17wKLpxaPBLYidV
https://chat.whatsapp.com/EZuNXTEuRaiH95bmPv1Lbc
https://chat.whatsapp.com/GP5dIGnhSPNBmatycitdR1
https://chat.whatsapp.com/Ef4K6wyXuXuIjJ6wxsHxzr
https://chat.whatsapp.com/D8IiSflmobc1cnbVpao7y2
https://chat.whatsapp.com/ICCit4HnXx98cPGZey2Oe6
https://chat.whatsapp.com/JAUU1mtxPpoJMp1K4bcXfz
https://chat.whatsapp.com/Be9G0f3KXDH7NJMqZrNuA2
https://chat.whatsapp.com/LDB9yHpu67oHMszwxHGUPV
https://chat.whatsapp.com/GkbXWyA9RnR9q1sKycfUZ4
https://chat.whatsapp.com/JUFESLY0dgxHZJsY8fArbW
https://chat.whatsapp.com/ENH1z0nUxzOC2W3BalAFkC
https://chat.whatsapp.com/G5MBW5QKaRl6HJhMl7hTwz
https://chat.whatsapp.com/GK2i45wZztAD7JU4KiaPAJ
https://chat.whatsapp.com/BSpjJhcEIcQDjX49vzluH5
https://chat.whatsapp.com/CsyMLiljrLILQJvqmaRDV9
https://chat.whatsapp.com/GTxxRwWKJTRJUJI1rsuCUu
https://chat.whatsapp.com/F6nUumtHmnq2v97Cd6Vnyt
https://chat.whatsapp.com/FdKMMQTEasq73PAkoSxHpL
https://chat.whatsapp.com/FD2CeNrDcIK9TajngVZwO3	
https://chat.whatsapp.com/H0qYvpa8UyrLADx1g1P91z					
https://chat.whatsapp.com/GNVAjGoIcarGvVndVYGXmt					
https://chat.whatsapp.com/F1rEHU7MOTM4oDFcKaT9ff					
https://chat.whatsapp.com/ExhE2X8Ac6O3f3PcRBmLWj					
https://chat.whatsapp.com/LMetrLYqSkFFDc8auQEpko					
https://chat.whatsapp.com/J6Xnr1m4zNxEdpJ4PyCWKi					
https://chat.whatsapp.com/FWCIqsZ7BqHDGFTDkyrT6H					
https://chat.whatsapp.com/JxlRyNGgYynCyS51fzW5QJ					
https://chat.whatsapp.com/JB14c4wRxoE2Qkb3qIqVVw				
https://chat.whatsapp.com/DTCxZNBWjrI5ZYaArFn8DI				
https://chat.whatsapp.com/HTCkwPhyMAG6QGCoBatncO					
https://chat.whatsapp.com/I13xPvfmLSy3JVxFrPwUyc				
https://chat.whatsapp.com/L2ISSEfNHLkCzvp6MzYMRN					
https://chat.whatsapp.com/J7tEBBN9Pka48RTSkcoUrZ				
https://chat.whatsapp.com/L5bfXZHEtoDF1631LAklOo					
https://chat.whatsapp.com/FyAtGSywLa18SP2zgLDtS7					
https://chat.whatsapp.com/FdVtpCSGtrkDTfuoQ66ETG					
https://chat.whatsapp.com/LkFWQG1Ie6Q0zs2Yh4UtyQ					
https://chat.whatsapp.com/E6kLV0M2CF1F0gYze4sEFB					
https://chat.whatsapp.com/IXhTqiu08MH0w5gn4bs3gs					
https://chat.whatsapp.com/Fre6Cf9aVKYCRpL1Syandx				
https://chat.whatsapp.com/LZODSnfXK23DHKZ8Psx9s8					
https://chat.whatsapp.com/HBEyNah2fk1I56Il4ggFPl					
https://chat.whatsapp.com/L3TmIaBFVmk2WJqLSKkrYp					
`;
